# Generated by Django 3.1.2 on 2020-10-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('component', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
